"""03

Revision ID: 071b7ebe6058
Revises: b4395128def3
Create Date: 2023-01-12 10:25:14.756723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071b7ebe6058'
down_revision = 'b4395128def3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###
