"""birth_date

Revision ID: 59c2ff6408c6
Revises: 071b7ebe6058
Create Date: 2023-01-12 10:47:11.618661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c2ff6408c6'
down_revision = '071b7ebe6058'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
